export const CONSTANTS = {
    storagePrefix: 'plasma_dark_theme_painter_',
    storageActivePrefix: 'plasma_private_dark_theme_painter_active',
    repoUrl: 'https://cdn-app.sberdevices.ru/shared-static/0.0.0/pixso-plugins/dark-themes-map.json',
    msgType: {
        loadStoredThemes: 'load-stored-themes',
        loadedStoredThemes: 'loaded-stored-themes',
        parseTokens: 'parse-tokens-from-frames',
        parsedTokens: 'tokens-from-frames-parsed',
        removeTheme: 'remove-theme',
        themeRemoved: 'theme-removed',
        getActiveTheme: 'get-active-theme',
        activeThemeFetched: 'active-theme-fetched',
        changeActiveTheme: 'change-active-theme',
        activeThemeChanged: 'active-theme-changed',
        createDarkClone: 'create-dark-clone',
        darkCloneCreated: 'dark-clone-created',
        hasDuplicates: 'frame-has-duplicates',
        createNew: 'create-new-dark-clone',
    },
};
